# From python 3
FROM python:3.6

# Install ansible
RUN pip install --pre ara
RUN pip install ansible

RUN apt-get update &&\
    apt-get install -y sshpass

COPY ansible-wrapper/ansible-playbook-wrapper /usr/bin/ansible-playbook-wrapper

WORKDIR /tmp/workdir

CMD ["ansible-playbook-wrapper"]
