version: "3.4"
services:

  # ara-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.ara-api
  #   image: "ara-api"
  #   ports:
  #    - 8000:8000
  #
  ara-web:
    image: "ara-web"
    build:
      context: .
      dockerfile: Dockerfile.ara-web
    ports:
     - 3000:3000
    # depends_on:
    #   - ara-api
